services:
  - mysql
  - redis-server
  - memcached
  - rabbitmq

notifications:
  slack:
    secure: Ziq6vzXmc1S+SZnJF7DyjprRgzZKvVK5TXtnNJAoH4EFchziCqko+75hMxDZ/6Y2kShcijgbzZSkIIVSiuYyx0Jgxdsmwed7yrs91uv2WsUw2/l+taOTBIAMa/m9PZppsRqmkywxWeeTPL6cf65Vg3PYRuqzj83nczUFJo4UNrA=

language: ruby

dist: precise
sudo: required
jdk:
  - oraclejdk8

before_install:
  # RUBY-2072 Prevent Travis setup failure before our test even starts
  - jdk_switcher use oraclejdk8
  - sudo rm -f /etc/apt/sources.list.d/travis_ci_zeromq3.list
  - gem --version
  - "echo 'gem: --no-rdoc --no-ri --no-document' > ~/.gemrc"
  - ./test/script/before_install/conditionally_upgrade_rubygems.sh
  - ./test/script/before_install/gemstash_mirror.sh
  - "echo GEMSTASH_MIRROR: $GEMSTASH_MIRROR"
  - bundle --version

install: bundle install --jobs 4

addons:
  apt:
    update: true
    packages:
      - libgmp3-dev
      - openssl
      - libssl-dev
      - build-essential
      - haveged

before_script: ./test/script/before_script/install_mongodb.sh

script: ./test/script/ci.sh

branches:
  only:
    - main
    - dev
    - release

rvm:
  # Run slowest builds first to try and optimize overall cycle time.
  - 2.6.1

jdk:
  - oraclejdk8

env:
  global:
    - BUNDLE_PATH=/home/travis/bundle
    - MONGODB=2.6.11
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx1024m -XX:CICompilerCount=1 -Xshare:auto"
    - JRUBY_OPTS="-Xcompile.invokedynamic=false -J-Djruby.compile.mode=OFF"
    - RBXOPT="-Xcompiler.no_rbc -Xint"
    - SERIALIZE=1
    - TESTOPTS="-v"
    - VERBOSE = 1
  matrix:
    - TYPE=UNIT ENVIRONMENT=rails30
    - TYPE=UNIT ENVIRONMENT=rails31
    - TYPE=UNIT ENVIRONMENT=rails32
    - TYPE=UNIT ENVIRONMENT=rails40
    - TYPE=UNIT ENVIRONMENT=rails41
    - TYPE=UNIT ENVIRONMENT=rails42
    - TYPE=UNIT ENVIRONMENT=rails50
    - TYPE=UNIT ENVIRONMENT=rails51
    - TYPE=UNIT ENVIRONMENT=rails52
    - TYPE=UNIT ENVIRONMENT=rails60
    - TYPE=UNIT ENVIRONMENT=norails
    - TYPE=FUNCTIONAL GROUP=agent
    - TYPE=FUNCTIONAL GROUP=api
    - TYPE=FUNCTIONAL GROUP=background
    - TYPE=FUNCTIONAL GROUP=database
    - TYPE=FUNCTIONAL GROUP=httpclients
    - TYPE=FUNCTIONAL GROUP=rails
    - TYPE=FUNCTIONAL GROUP=serialization
    - TYPE=FUNCTIONAL GROUP=sinatra
    - TYPE=FUNCTIONAL GROUP=rest
    - TYPE=FUNCTIONAL GROUP=background_2
    - TYPE=FUNCTIONAL GROUP=infinite_tracing
    - TYPE=NULLVERSE

matrix:
  fast_finish: true
  exclude:
    # 2.6
    - rvm: 2.6.1
      env: TYPE=UNIT ENVIRONMENT=rails30
    - rvm: 2.6.1
      env: TYPE=UNIT ENVIRONMENT=rails31
    - rvm: 2.6.1
      env: TYPE=UNIT ENVIRONMENT=rails32
    - rvm: 2.6.1
      env: TYPE=UNIT ENVIRONMENT=rails40
    - rvm: 2.6.1
      env: TYPE=UNIT ENVIRONMENT=rails41
