name: Docker Test
on: [push, pull_request]
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}

# name: Docker Test

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the main branch
# on: [push, pull_request]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   docker-test:
#     runs:
#       using: 'docker'
#       image: 'Dockerfile'
#       args:
#       - 'bzz'
#       entrypoint: 'entrypoint.sh'
#     env:
#       LANG: C.UTF-8
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup Ruby
#         uses: actions/setup-ruby@v1
#         with:
#           ruby-version: 2.5
#       - name: show ulimit
#         run:  ulimit -S -n 4096 && ulimit -n
#       - name: Bundle
#         run: bundle install
#       - name: rake test
#         run: bundle exec rake test TESTOPTS="--verbose"
