name: Experiment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  experiment:
    runs-on: ubuntu-latest
    env:
      LANG: C.UTF-8
    steps:
      - uses: actions/checkout@v2

      - name: Build that Ruby
        id: build-that-ruby
        uses: ./.github/actions/experiment
        with:
          ruby-version: 2.3

      - name: show output
        run: echo "${{ steps.build-that-ruby.outputs.results }}"

      - name: show me something
        run: ruby --version
