name: Experiment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  experiment:
    env:
      LANG: C.UTF-8
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [ "2.3.8" ]
        # ruby-version: [ "2.0.0-p648", "2.1.10", "2.2.10", "2.3.8", "2.4.10", "2.5.8", "2.6.6", "2.7.1" ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: ruby-cache
        with:
          path: $HOME/.rubies/ruby-${{ matrix.ruby-version }}
          key: v1-ruby-cache-${{ matrix.ruby-version }}-${{ runner.os }}
          restore-keys: |
            v1-ruby-cache-${{ matrix.ruby-version }}-${{ runner.os }}

      - name: Build Ruby ${{ matrix.ruby-version }}
        id: build-ruby
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Show versions
        run: |
          echo $PATH
          ls $HOME/.rubies/**/bin/*
          which ruby
          ruby --version
          ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
          gem --version
          bundle --version
