name: Infinite Tracing Test

on: 
  push: 
    branches:
      - main
      - dev
  pull_request:

jobs:
  infinite-tracing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.5.8, 2.6.6, 2.7.1]
    steps:
      - uses: actions/checkout@v2

      - name: Build Ruby ${{ matrix.ruby-version }}
        uses: ./.github/actions/build-ruby
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Bundler install
        run: bundle install

      - name: Run Infinite Tracing Tests
        uses: nick-invision/retry@v1.0.0
        with:
          timeout_minutes: 20
          max_attempts: 3
          command:  bundle exec rake test:multiverse[group=infinite_tracing,verbose]
