on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  Check_contributor_handle:
    runs-on: ubuntu-latest
    env:
      admins: "['angelatan2', 'elucus', 'fallwith', 'kaylareopelle', 'tannalynn']"
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
      - name: Label community issue
        uses: actions/github-script@v5
        with:
         script: |
           github.rest.issues.addLabels({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             labels: ['community']
           })
        if: |
          !contains(fromJson(${{ env.admins }}), github.event.issue.user.login) &&
          !contains(fromJson(${{ env.admins }}), github.event.pull_request.user.login)
