name: Create Prerelease

on:
  workflow_dispatch:
  push:
    branches:
      - create_prerelease_automation_job

jobs: 
  create_prerelease:
    runs-on: ubuntu-22.04
    steps:
    - uses: ruby/setup-ruby@7d546f4868fb108ed378764d873683f920672ae2 # tag v1.149.0
      with:
        ruby-version: 3.2

    - name: Checkout code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0

    # Update files for release
    - run: bundle
    - run: bundle exec rake newrelic:version:bump
    # - run: bundle exec rake newrelic:config:whateverhannahismaking

    - name: Set tag name
      run: echo "prerelease_tag=$(bundle exec rake newrelic:version:current)-pre" >> $GITHUB_ENV

    - name: Create pull request
      run: |
        git checkout -b "prerelease_updates_${{ env.prerelease_tag }}"
        git add --all
        git config --global user.email "ruby-agent@newrelic.com"
        git config --global user.name "Github bot"
        git commit -m "bump version"
        git push --set-upstream origin prerelease_updates_9.3.0-pre
        gh pr create --label $LABEL --title $TITLE --body $BODY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TITLE: "TEST: IGNORE PLS: Prerelease #{{env.prerelease_tag}}"
        BODY: "Updates the version number, changelog, and newrelic.yml(if it needs updating). This is an automated PR"
        LABEL: prerelease
       
    - name: Create pre release tag
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # tag v0.1.15
      with:
        tag_name: ${{ env.prerelease_tag }}-test
        name: ${{ env.prerelease_tag }}-test
        target_commitish: prerelease_updates_${{ env.prerelease_tag }}
        prerelease: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
