name: build

on:
  - push

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: Build Ruby
    steps:
      - name: Build that Ruby
        with:
          ruby-version: "2.0.0-p648"
          test-suite: test
        uses: ./.github/actions/build
